### ISSUE TITLE
STT0060: Create a training data from gen drupchen data.

### ISSUE THREAD

**Issue by gangagyatso4364** [OpenPecha/stt-training-data#1]
### Description 
We need to create stt training data from the gen drupchen data. Split audio index from original full audio is given and the transcription for corresponding indexes are given as well. we just have to split the audios from full audio and upload it to s3://monlam.ai.stt/wav16k/ with proper file name. 

[LINK TO DRIVE](https://drive.google.com/drive/folders/1ChX5UQJI4Umvo0mpNPJgmMB0CEs_NEYx)
Example:
 ```
file_name, dept, audio_url, audio_duration_in_seconds, transcript
STT_TT_D[AUDIO_ID]_order_id_[start]_to_[end], TT, https://example.com/wav16k/STT_TT_D[AUDIO_ID]_order_id_[start]_to_[end].wav, [duration], [transcript]
```

### Completion Criteria
```
file_name, dept, audio_url, audio_duration_in_seconds, transcript
STT_TT_D001_0001_0_to_3000, TT, https://d38pmlk0v88drf.cloudfront.net/wav16k/STT_TT_D001_0001_0_to_3000.wav, 3, ཀྲུང་གོའི་ཕྱོགས་ཀྱིས་ཅོར་ཏན་གྱིས་ གླེང་སྟེགས་ཀྱི་ཐུན་མོང་ཀྲུའུ་ཞིའི་རྒྱལ་ཁབ་ཡིན་པའི་ཆ་ནས་མཐུན་སྦྱོར་བྱ་བ་མང་བོ་བསྒྲུབ་པར་གཟེངས་བསྟོད་བྱེད་པ་དང་།
STT_TT_D001_0002_3001_to_5000, TT, https://d38pmlk0v88drf.cloudfront.net/wav16k/STT_TT_D001_0002_3001_to_5000.wav, 3, ཀྲུང་གོའི་ཕྱོགས་ཀྱིས་ཅོར་ཏན་གྱིས་ གླེང་སྟེགས་ཀྱི་ཐུན་མོང་ཀྲུའུ་ཞིའི་རྒྱལ་ཁབ་ཡིན་པའི་ཆ་ནས་མཐུན་སྦྱོར་བྱ་བ་མང་བོ་བསྒྲུབ་པར་གཟེངས་བསྟོད་བྱེད་པ་དང་།
STT_TT_D002_0001_0_to_5000, TT, https://d38pmlk0v88drf.cloudfront.net/wav16k/STT_TT_D002_0001_0_to_5000.wav, 3, ཀྲུང་གོའི་ཕྱོགས་ཀྱིས་ཅོར་ཏན་གྱིས་ གླེང་སྟེགས་ཀྱི་ཐུན་མོང་ཀྲུའུ་ཞིའི་རྒྱལ་ཁབ་ཡིན་པའི་ཆ་ནས་མཐུན་སྦྱོར་བྱ་བ་མང་བོ་བསྒྲུབ་པར་གཟེངས་བསྟོད་བྱེད་པ་དང་།
```

### SubTask
- [x] Create a script named `split_audio.py` to split the large audio file into smaller segments based on the corresponding CSV file.
- [x] Develop a script to generate the CSV file in the required format (file_name, dept, audio_url, audio_duration_in_seconds, transcript).
- [x] Upload the split audio files to the S3 bucket: `s3://monlam.ai.stt/wav16k/.`
- [x] Upload the generated CSV file to the S3 path: `s3://monlam.ai.stt/backup/drupchen_training.csv.`
